name: React/Jest/S3 - test, build and deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install - test - eslint
      run: |
        npm install
        npm run test
        npm run lint
    - name: build assets
      run: npm run build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: build assets
      run: npm run build    
    - name: deploy
      run: aws s3 rm ${{ secrets.S3_BUCKET }} --recursive --exclude "assets/*" && aws s3 cp ./dist ${{ secrets.S3_BUCKET }}/ --recursive
    - name: invalid cloudfront cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CDN_DISTRIBUTION_ID }} --paths "/*"
